# Makefile for CoLab 02
# Compile command that names the output file to calculate.out, also compiles with warnings
compile:
	g++ -Wall calculate.cpp -o calculate.out
# Runs the calculate.out file
run:
	./calculate.out
# Removes all .out files
clean:
	rm *.out
