# Makefile for calculate.cpp & calculate2.cpp
# Compile command for time to pay off loan calculator
compile:
	g++ calculate.cpp -o calculate.out
# Compile command for 2nd program w/ extra credit and interest calculations
compile2:
	g++ calculate2.cpp -o calculate.out
# Runs the program command:
run:
	./calculate.out
# Clean command
clean:
	rm *.out
