# My second makefile
# Reminders:
# Lines containing commands must start with a tab and not spaces!
# Pound symbol will let you do comments
# 
# make compile:
# default command that compiles the program under p1.exe
compile:
	g++ project-1.cpp -o p1.exe
# make run:
# runs the p1.exe output file from project-1.cpp
run:
	./p1.exe
# make clean
# removes all .exe files and cleans the directory
clean:
	rm *.exe
